### ISSUE TITLE
About: USD value amount navigates to the 1020 error page

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1052]
Reproducible in Prod/Stage/Dev
It might be my regional setting, but I'd better report this issue

1. Open About Page
2. Press on the `USD 390M` link

**AR**: user is navigated to the https://explore.flashbots.net/ page with 1020 error
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f0c5b91c-7edf-4f62-83c2-4dee55176813)
![image](https://user-images.githubusercontent.com/70885163/126958267-b1f73b74-446a-4297-92f9-1a6026c4d515.png)

**ER**: no error on the page?

**Comment by W3stside** [comment]
@avsavsavs

**Comment by avsavsavs** [comment]
this looks weird, the page does work for me. Maybe the link is broken in the code or wrongly referenced. It is a good catch, because we need to change the number to 797 M. @elena-zh Could you do such change or point me to where the page is and I will create the PR? 

Thank you

![image](https://user-images.githubusercontent.com/80408352/127110680-3f76c835-ab4d-4a4f-bf24-9f185cf8ae3a.png)

**Comment by elena-zh** [comment]
Hi @avsavsavs , here the  page https://cowswap.exchange/#/about
![image](https://user-images.githubusercontent.com/70885163/127120921-3cf4f367-e6dd-455f-ac18-fe5e1441ebbe.png)

Thanks!

**Comment by avsavsavs** [comment]
Yes, I meant wheres the file in the github that has that page @elena-zh. This way I can push the PR with the changes

**Comment by elena-zh** [comment]
@avsavsavs , 
About: https://github.com/gnosis/cowswap/blob/develop/src/custom/pages/About/index.tsx
FAQ: https://github.com/gnosis/cowswap/blob/develop/src/custom/pages/Faq/index.tsx
