### ISSUE TITLE
Implement gas estimation display/notification on UI

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1693]
Design was implemented and discussed in #1375

> Right now, CowSwap users have no way to tell (using the UI alone) what's the current gas price.
> Although orders placed cost no gas, the fees charged on the execution are dependent on gas prices.
> So it might still not be a good idea to place an order during gas spikes, as you can spend a large amount in the trade you might not want to.
> 
> On top of that, when Smart contract wallet orders are integrated, these users will have to send onchain txs when placing orders.

**Comment by elena-zh** [comment]
@alfetopito , do we still have this task in the priority list, or should we close this for now?

**Comment by alfetopito** [comment]
Uniswap has added it and since I'm merging with their latest updates, we should get this for "free"

Check the bottom right of their app:
<img width="165" alt="Screen Shot 2022-03-02 at 11 08 26" src="https://user-images.githubusercontent.com/43217/156431311-21c4e5c1-6506-481c-b9c0-b316489edf5c.png">

**Comment by elena-zh** [comment]
Cool, thanks!
I'm closing the task then.
