### ISSUE TITLE
[Affiliate] - Make change the network into a link to change the network

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1774]
**Description**
It could be a bit more straight forward if the user could click on **change the network** in the message to switch networks.
<img width="879" alt="Bildschirmfoto 2021-11-04 um 11 19 58" src="https://user-images.githubusercontent.com/34510341/140297389-6c595da6-c36d-4626-be9c-6b986dcf8b19.png">

**Comment by elena-zh** [comment]
Related to #1575, #1675 (added in order to link these issues)

**Comment by elena-zh** [comment]
Hi @alfetopito , are we OK to implement this change?
If yes, what exactly should be when a user presses on the 'Change the network' on the banner? 
As I can suppose, we could send a request to switch to the Mainnet in the connected MM that supports network switching, but what about WC connection?

Thanks

**Comment by alfetopito** [comment]
I'm not sure myself, I'll check with the team.

Regarding the behaviour on WC or unsupported wallets, it would be the same as today with the network switcher. Not possible.
Only works for wallets that support that.

I personally don't think this is worth the effort, mostly because of that (behaviour for wallets that don't support it)
But anyway, if this is shown it's likely the wallet supports mainnet, so my argument is not so strong.

**Comment by anxolin** [comment]
I wouldn't do it. There's already a fairly easy way to change networks. I agree could be nice to have, but I don't think we should invest in this 

Thanks for the suggestion anyways

**Comment by elena-zh** [comment]
I'm closing the issue then. 
Thank you!
