### ISSUE TITLE
[1.4.2]  issue with upload IPFS: referral data is not displayed in an account

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1821]
**Updated description:** 
my referral code was not applied to the trade: 
![image](https://user-images.githubusercontent.com/70885163/141288534-6680c83a-9d71-477c-998d-86168d4f2081.png)

referral code was https://cowswap.staging.gnosisdev.com/#/?referral=0xFa433e5B2B5Ab9440039b4dd23ED2D3e151A8AbD

But I'm not sure whether it is so or not.. Might be a BE issue something like #1717

**Comment by elena-zh** [comment]
So, the case is: 
1. share a referral code to an account
2. switch to another account
3. go back to the 1st account
4. navigate to the profile page

**AR**: local storage is cleared out, transactions history is missing

**Comment by elena-zh** [comment]
As an additional result, my referral code was not applied to the trade: 
![image](https://user-images.githubusercontent.com/70885163/141288534-6680c83a-9d71-477c-998d-86168d4f2081.png)

referral code was https://cowswap.staging.gnosisdev.com/#/?referral=0xFa433e5B2B5Ab9440039b4dd23ED2D3e151A8AbD

But I'm not sure whether it is so or not.. Might be a BE issue something like #1717

**Comment by josojo** [comment]
It's an issue with the upload of ipfs:

in staging, we were trying to get the data at 11:50 and got it on the frist try:
https://logs.gnosis.io/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-150m,to:now))&_a=(columns:!(_source),filters:!(),index:'63bc0b10-5f93-11e9-bf17-fbe383fc7c9c',interval:auto,query:(language:kuery,query:'log:%22bafybeift2jrloyiu56rlkurkywfuc6en62s3wspu65anjyemp7etttb7sq%22'),sort:!())

In production, we were trying to get the data at 11:43 and it was not yet available:
https://logs.gnosis.io/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-150m,to:now))&_a=(columns:!(_source),filters:!(),index:'63bc0b10-5f93-11e9-bf17-fbe383fc7c9c',interval:auto,query:(language:kuery,query:'log:%22bafybeift2jrloyiu56rlkurkywfuc6en62s3wspu65anjyemp7etttb7sq%22'),sort:!())

Hence, it seems to be an issue with a non-timely upload of the ipfs information.

In order to counter it, I will try retry it more often.. currently it is only to be re-tried 3 times. But any ideas are welcome to make the upload smoother as well. Are you guys using our endpoint: gnosis.mypinata.com?

**Comment by elena-zh** [comment]
The current issue contains 2 parts: 
1. local storage is cleared out after switching accounts
2. BE issue with upload IPFS

I leave the current task opened for BE issue with upload IPFS as it is already connected with https://github.com/gnosis/gp-dune-bridge/pull/46
and will create a separate issue for local storage: #1822

**Comment by josojo** [comment]
BE issue is fixed:
https://protocol-affiliate.gnosis.io/api/v1/profile/0xFa433e5B2B5Ab9440039b4dd23ED2D3e151A8AbD
shows the 1 referral trade.

**Comment by josojo** [comment]
@elena-zh could you maybe please test it one more time with the new BE version. It should really work! but it was super hard to debug, as I did not know when the ipfs file was uploaded etc. Pinata provides very little data.

**Comment by elena-zh** [comment]
Yes, I will retest it very soon!

**Comment by elena-zh** [comment]
@josojo , I no longer able to reproduce this issue. 
Thank you!

**Comment by alfetopito** [comment]
> Are you guys using our endpoint: gnosis.mypinata.com?

No because as far as I checked, the custom gateway is for read. Also, their SDK did not provide a way to set custom endpoints https://www.npmjs.com/package/@pinata/sdk
