### ISSUE TITLE
'Wrap my XDAI/ETH' section is enabled when a wallet is not supported

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1845]
Reproducible on Prod

1. Connect to a wallet that is not supported
2. Select XDAI/ETH in the From section
3. Select a token to buy
4. press on the Wrap my  XDAI/ETH button

**AR**: transaction is running, a request to sign the transaction is sent to the connected unsupported wallet
![wrap.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3c155ddd-24ce-40b9-b4d2-67a1aff47444)

**ER**: the button is disabled, 'Wallet Unsupported' is displayed on it

**Comment by TrustwalletAdmin** [comment]
Hello, good day , due to time difference and interval we are not supposed to text you first at this time,but we were worried and concerned about the support you need,and please note..non of our admins will ask you for your private key, kindly beware of scammers,By the way ;has anyone been able to answer and solve the complaint for you among our admins?

**Comment by TrustwalletAdmin** [comment]
Your error message seems quite interesting , familiar and it is a common error,as we solved an issue related to this a couple of minutes ago ,be rest assured as I will commit my time in trying to solve this complaint also as your satisfaction keeps us going as a company
