### ISSUE TITLE
Claim: show token's account info when claim on behalf

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2083]
It would be nice to have a message 'You have successfully claimed X vCOW for an <account>' , in the activity modal when claim on behalf on an account. 
https://github.com/gnosis/cowswap/issues/2083#issuecomment-1023130323

**Comment by anxolin** [comment]
I think this doesn't work anymore AFAIT

reopen if it's not the case

**Comment by elena-zh** [comment]
Hey @anxolin , I still do not see this into in the Activity modal. 
That's why I prefer leaving it opened
![image](https://user-images.githubusercontent.com/70885163/151225187-73e4efcc-6b87-4212-9a88-2e775045e7ff.png)

**Comment by anxolin** [comment]
But, let me see if i get the issue correctly. You are suggesting to be more specific with the message, and instead of `Claim 1.766 Cow` [Executed] you would want to add something more like "You have successfully claimed..."

I believe the activity have listed operations, and they are described in a neutral way, so the message would work for [Executed] or [Pending] or [Failed]

I don't think we are personalising the message for other operations, and I would think now we wrote "Claim" instead of "Claiming" the message is clear and works for all 3 cases. 

Let me know if im missing sth

**Comment by elena-zh** [comment]
@anxolin , no exactly. 
I mean to separate actions in the Activity modal: 
 - claim for myself: leave it as it is: Claim 1.766 Cow [Executed]
 - claim on behalf: Claim 1.766 Cow for <account>[Executed]

**Comment by anxolin** [comment]
Ok! thanks for clarifying. The thing is, the message will be a bit long if we include the proposed one (cause the address is long).
If im not mistaken, the message currently is just a text, so we don't have an easy way to add a link and shorten the URL. Also, probably not worth it. 

We can keep it open, but i think it will be not worth doing this one personally
