### ISSUE TITLE
Claimed! screen appears again and again when open Claim page after successful claim

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2219]
1. Do a successful claim to get 'Claimed!' screen
2. Go to the profile page
3. Go back to the Claim! page

**AR**: 'Claimed!' screen with confetti appears again and again
Video: https://watch.screencastify.com/v/9YBOHgQeZ3j7yVBesn4D

**ER**: user is navigated to the main claim page

**Comment by elena-zh** [comment]
Additionally, when a user gets back, Claimed amount is no longer displayed on the form
![image](https://user-images.githubusercontent.com/70885163/151173904-a35b6700-dd2c-49f6-9fef-507f34791955.png)

**Comment by anxolin** [comment]
It's a feature, not a bug 😆

You can revive the joy of receiving tokens multiple times!

I think is not worth changing this

**Comment by elena-zh** [comment]
@anxolin , but what if a user still has some options to claim? 
He/she needs to update the page in order to see them.. 
Moreover, as I has mentioned above. Claimed amount of tokens disappears on the screen when go back.. 
So I would leave the issue opened.

**Comment by anxolin** [comment]
Good point! Although, i don't feel is to important for this reason:

- Claiming is expensive, it will likely be done in one tx rather than several
- It's kind of nice to see the celebration over and over, with the actions to join the community :) 
- If the user wants to claim again, i think they would naturally REFRESH the web, getting back the claiming form
- Additionally, the user can click here, to claim more:
![image](https://user-images.githubusercontent.com/2352112/151353164-46ac673a-d00a-40ca-9605-91bbf2e7c389.png)

The fact the claimed amount dissapears, could be good to fix, i agree. However its also just a nice to add, since it can be seen in the activity, and was display before, and the success page shows some non-broken message

@nenadV91 not too important, but do you know why we loose the total claimed when we navigate? I thought we were saving this in redux store, so i believe it should also be there when we navigate back.
