### ISSUE TITLE
[1.10] Do now show 'available for claims' banner when connected to Gnosis Safe

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#2333]
Originally reported in https://github.com/gnosis/cowswap/pull/2313#issuecomment-1023333630

I have just retested changes when connected to Gnosis Safe: is it possible to have safe with the same address in all networks? 
![image](https://user-images.githubusercontent.com/70885163/151388115-c518582f-9b2a-4a02-beaa-54dd8636c742.png)

If not, I'd rather not to show this message when connected to Gnosis safe

**Comment by alfetopito** [comment]
That's a use case that shouldn't happen with real data.
Claims will only be awarded in 1 network, be it on Gchain or mainnet.

In the special case of smart contracts, the claim will only be available in the same network where the wallet interacted with the protocol, because we cannot guarantee the address will exist on another chain.

All of this is to say, you won't see this message with real claims, so there's no action to take.

Closing the issue
