### ISSUE TITLE
Confirmation Modal Trust Wallet shows raw data

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#593]
**Is your feature request related to a problem? Please describe.**

The layout in the confirmation modal (trust wallet) is really bad. Can we somehow influence it, e.g.  limit the info shown 
![1620206403639](https://user-images.githubusercontent.com/34510341/117120999-57848600-ad94-11eb-8dcd-0a7796248418.jpg)

**Comment by alfetopito** [comment]
I agree, it's awful.
Unfortunately, that's how they display the typed data via wallet connect.

One simple alternative for us would be to go straight to `eth_sign` instead of the typed data signature.
That's the fallback we use for Ledger and for Trustwallet itself when using the dApp browser.

The other option is reach out to them and ask for a nicer representation.

**Comment by anxolin** [comment]
I'm inclined for the option to reach out to them. 

@annamsgeorge maybe even tagging them in Tweeter. When we announce WC compatibility, we can tag directly trust wallet, with a picture and making them to present nicer the signed information

Maybe it happens faster, and also give us some visibility. WDYT?

**Comment by anxolin** [comment]
Moving to current sprint, just to make a decision or reach the team and close this issue.

I don't think `eth_sign` is the way to go, because is a dangerous operation, it should disappear from the wallets in favour of the safer ones.
Some wallets like MM allow to use it, but they show a scary message.

**Comment by elena-zh** [comment]
HI there!
I was not able to connect the app with TrustWallet installed in iOS, while connection with the app in Android works fine. 
Has anybody experienced this issue as well?

Thanks

**Comment by elena-zh** [comment]
Upd: the issue with iOS connection is related to a 'watch-only' wallet. 
I have had imported watch-only account in my TrustWallet app, and I did not have a possibility to connect the app with the wallet. 
In Android I got an explanation message about it...

**Comment by alfetopito** [comment]
So, is the issue with the wallet on iOS?

**Comment by elena-zh** [comment]
The issue with the TrustWallet in iOS that it does not warn a user about using a 'watch-only' wallet there, that is why it is impossible to connect the app.

**Comment by alfetopito** [comment]
I see. In that case, out of our control.
Could you report that on their repo, though? https://github.com/trustwallet/wallet-core/issues

**Comment by elena-zh** [comment]
Done! 
https://github.com/trustwallet/wallet-core/issues/1536

**Comment by anxolin** [comment]
Closing and creating https://github.com/trustwallet/wallet-core/issues/2058
