### ISSUE TITLE
Price/fee is wrong when swapping tokens

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#604]
**Describe the bug**

**How to Reproduce**
https://github.com/gnosis/gp-swap-ui/pull/602#pullrequestreview-653704054

**Comment by anxolin** [comment]
Probably related to https://gnosisinc.slack.com/archives/CPZA1AGKY/p1620325243303700

**Comment by W3stside** [comment]
@anxolin @alfetopito I'm not convinced this is happening anymore, just battle tested it with a bunch of pairs on rinkeby switching like crazy and changing amounts and nothing. tested in production.

maybe this was due to the `useDebounce` before we added the `useDebounceWithForceUpdate` which listens for input field type change. I believe this should be closed.

**Comment by anxolin** [comment]
> @anxolin @alfetopito I'm not convinced this is happening anymore, just battle tested it with a bunch of pairs on rinkeby switching like crazy and changing amounts and nothing. tested in production.
> 
> maybe this was due to the `useDebounce` before we added the `useDebounceWithForceUpdate` which listens for input field type change. I believe this should be closed.

Okay, I let @alfetopito close it, if he considers this solved

**Comment by alfetopito** [comment]
All good, can no longer reproduce
