### ISSUE TITLE
Strong price fluctuation- worse price than Para

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#822]
**Description**
Strong price fluctuation in short time period. 
Price is quite off compared to Paraswap but then recovers and then drops again

**How to Reproduce**
1. Go to CowSwap
2. Chose BAL- USDT
3. Chosse max value
4. See price
5. Wait for price updates
6. To token fluctutates - worse than paraswap

**Expected behavior**
The receiving tokens( before fee) should be equal or better than Paraswap

**Screenshots**
Sudden droop in receiving tokens
<img width="1433" alt="Bildschirmfoto 2021-06-30 um 09 56 39" src="https://user-images.githubusercontent.com/34510341/123924929-b4fb1480-d98a-11eb-8fd9-92a2b7579efb.png">
Shortly after the correct amount is back:
<img width="1430" alt="Bildschirmfoto 2021-06-30 um 09 57 37" src="https://user-images.githubusercontent.com/34510341/123925063-d65c0080-d98a-11eb-87e2-9511e7b6d40e.png">
And then it is gone again:
<img width="625" alt="Bildschirmfoto 2021-06-30 um 09 59 24" src="https://user-images.githubusercontent.com/34510341/123925143-ebd12a80-d98a-11eb-9ebc-3c9e6aa1b7bc.png">

**Additional context**
<img width="1440" alt="Bildschirmfoto 2021-06-30 um 09 57 01" src="https://user-images.githubusercontent.com/34510341/123925463-38b50100-d98b-11eb-88ce-3f4aef327e24.png">

This fluctuation happened for quite a while then it started to show the error message: Fees exceed from amount
After waiting a little bit longer the fluctuation was back
Only saw it for this specific token pair. 
Will see if this occurs for others

**Comment by anxolin** [comment]
I belive is mostly because your 0.41 is very close to the fee. So fluctuations in it makes you to receive almost none or only a few USDT. And at times it can be even higher the fee than the sell amount making it imposible to even trade.

There's an issue related to this I notice, and is the price being super off. Theoretically doesn't need to take the fee into account. I would close this issue if and leave https://github.com/gnosis/cowswap/issues/828 if this was the only problem. 

The fluctuation is expected. The fee depends of current market conditions (ETH price, Gas Price, Pool sizes). And a few USD variations are expected.

**Comment by W3stside** [comment]
> This fluctuation happened for quite a while then it started to show the error message: Fees exceed from amount
> After waiting a little bit longer the fluctuation was back

yes this was happening because as Anxo wrote your input amount was very close to the fee. The fluctuations were happening as the fee was updating and sometimes being > than input (hence the error message)

**Comment by W3stside** [comment]
@MareenG closing this but feel free to re-open it if you feel it should be
