### ISSUE TITLE
WC not working on mobile

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#862]
**Description**
The WC link is not shown when visting cowswap on a mobile device

![1625563037359](https://user-images.githubusercontent.com/34510341/124575717-ec1a6b80-de4b-11eb-99fe-edab3664fcc9.jpg)

**Comment by elena-zh** [comment]
@MareenG , this might be an expected behavior for this module when you open the app in Android. 
Once you press on the 'Connect' (verbinden) button, it will search for all installed wallets that support WC in your mobile device and will propose them to select for connection.
In iOS, it will show all possible connection apps instead..

**Comment by alfetopito** [comment]
> @MareenG , this might be an expected behavior for this module when you open the app in Android.
> Once you press on the 'Connect' (verbinden) button, it will search for all installed wallets that support WC in your mobile device and will propose them to select for connection.
> In iOS, it will show all possible connection apps instead..

That's interesting, I had no idea it worked like that :)

**Comment by elena-zh** [comment]
@alfetopito , I tested and investigated these issues in the GA project. 
[Here](https://github.com/gnosis/ido-ux/issues/650#issuecomment-855770392) were reported my findings.
In Android, from my perspective, searching for installed apps in the device looks more accurate and pretty solution then displaying all of them, like it is in iOS. Due to half of these apps navigate to 404 page, or nothing happens when you select any if it is not installed to your iOS device (see case 4 [here](https://github.com/gnosis/ido-ux/issues/650#issuecomment-855770392))
In addition, I recorded you videos to compare:
Android: 
https://user-images.githubusercontent.com/70885163/124723933-3109d500-df14-11eb-82d2-0b222b40ba26.mp4


iOS: 
https://user-images.githubusercontent.com/70885163/124723944-336c2f00-df14-11eb-9c34-254d8277cec1.mp4

**Comment by MareenG** [comment]
I also didn't know it worked like this :). 

However, I noticed today that it still doesn't work really for me. I can connect with MM but couldn't sign a transaction (my phone currently has some issues with MM and I ordered a testphone) However, the other wallets like Trust Argent , etc don't connect at all. Is anyone experiencing the same or is it just my phone?

**Comment by elena-zh** [comment]
@MareenG , 
 - I was able to connect the app with TrustWallet in iOS and in Andriod. However, I cannot run tests there as TrustWallet does not support Rinkeby, and I do not have assets in the Mainnet=(
![Skype_Picture_2021_07_07T09_21_31_235Z](https://user-images.githubusercontent.com/70885163/124734702-1177aa00-df1e-11eb-997c-85bd2ff75160.jpeg)

 - I was able to place an order using WC with Metamask in iOS.
![Skype_Picture_2021_07_07T09_21_38_027Z](https://user-images.githubusercontent.com/70885163/124734726-163c5e00-df1e-11eb-8237-66189888c832.jpeg)

 - The only connection issue I face is that the app does not listen the 'Cancel' connection status when user cancels it in the connection wallet. The app is still hanging in the 'Initializing..' state instead of showing a connection error. If this issue does not exist on the board, I will create it then..
https://user-images.githubusercontent.com/70885163/124734829-28b69780-df1e-11eb-8bd0-9400168a82e4.mp4
 

 - I was able to run transactions using WC with MM in Android. But.. not from the 1st try. 
The issues I faced:
1. Approve token transaction did not appear in my transactions list
2. 1st try: I signed transaction, but it did not appear in my transaction list
3. 2nd try: message to sigh transaction did not appeared in my MM account
4. 3rd try: I killed MM, then started the signing process again --> transaction was successful

https://user-images.githubusercontent.com/70885163/124736199-71228500-df1f-11eb-8d51-d3e7c5f206a3.mp4
