### ISSUE TITLE
Rounding of fees to 0 for small receiving amounts

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#886]
**Description**
If the amount of the receiving token is quite low we display a fee of 0. This is probably due to rounding. 
However, the actual fee is not 0

**How to Reproduce**
1. Go to cowswap
2. Place an order e.g. Dai vs cBat (Rinkeby) 
4. See the displayed Fee

**Expected behavior**
A fee bigger than 0 should be displayed

**Screenshots**
<img width="602" alt="Bildschirmfoto 2021-07-07 um 12 02 58" src="https://user-images.githubusercontent.com/34510341/124751387-dd54b700-df26-11eb-8f98-b83938eeeb7c.png">
<img width="1374" alt="Bildschirmfoto 2021-07-07 um 12 04 24" src="https://user-images.githubusercontent.com/34510341/124751409-e2b20180-df26-11eb-9f7c-31397686152b.png">

This is rather an edge case probably won't happen but we should find a solution how to display the fees in such cases

**Comment by alfetopito** [comment]
Very likely related to https://github.com/gnosis/cowswap/issues/800

**Comment by W3stside** [comment]
the issue lies with `formatSmart` inside cowswap ui (the custom one wrapping the dex - js one) as it passes the amount of decimals to show, and sets the low limit to something tiny, i think the constant is set to: 0.0000000000000000001. 

what this means is that if the amount is 0.0000005 and the decimals to show is set to 4, then it will show 0. and not the low limit as the low limit is much smaller than the set decimals and the actual amount..

we should either fix dex-js formatSmart and/or set the limit manually. i changed the fn inside cwswap to accept an options object where we can set the smallLimit manually.

**Comment by alfetopito** [comment]
I think the issue is slightly different.
Just found this on https://github.com/gnosis/cowswap/pull/1091

The problem there was that to come from the stored value into `formatSmart`, we use `toFixed()` without parameters, which defaults to 4 decimals.
This _could_ be the same issue.
