### ISSUE TITLE
UX - USD price estimate 

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#949]
**Description**
I like that we now display the $ estimate. However the way we currently display it give the impression that we offer quite a bad deal. 
<img width="494" alt="Bildschirmfoto 2021-07-15 um 15 37 41" src="https://user-images.githubusercontent.com/34510341/125797495-189545c0-b6e0-4ce1-945b-92b257017cbd.png">

I think even if we implement the tool tip as before,
<img width="227" alt="Bildschirmfoto 2021-07-15 um 15 39 42" src="https://user-images.githubusercontent.com/34510341/125797791-e1a35c4a-771e-456f-b55a-eaa28778f78b.png">

the first impression in the displayed case could be still that is is a bad deal.

**Comment by alfetopito** [comment]
I think it looks like a bad deal because it actually is, hehe
This is a small amount not usually worth trading.

Having said that, I understand your point, and it's something we are aware.
These concerns have been/will be addressed with the re-work of the inputs we already have the UI designed.
We have not started working on it yet, though.

**Comment by MareenG** [comment]
Closing as the design overhall addressed this issues and we now display the fee breakdown better .
